### ISSUE TITLE
I followed your docker installation method to install in linux and reported the following error

### ISSUE THREAD

**Issue by bukong6** [danny-avila/chatgpt-clone#14]
Connected to MongoDB
npm ERR! path /api
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh -c node server/index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-09T08_22_49_452Z-debug-0.log

> chatgpt-clone@1.0.0 start
> node server/index.js

Server listening at http://localhost:3080
Connected to MongoDB

**Comment by bukong6** [comment]
do you know why

**Comment by danny-avila** [comment]
@bukong6 this is happening because it’s taking too much resources, what are the specs on your Linux machine? I’ve run this on 2 different machines successfully with docker. Do you get any errors when you first build before using docker-compose? Not sure if it will help, but I can try prebuilding the images and sharing them on dockerhub

**Comment by bukong6** [comment]
Thank you for solving the problem just now. The server is 8 cores. It is estimated that it is just an operation problem
